services:
  traefik:
    image: traefik:v2.10
    container_name: hk_traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=admin@hkemprestimos.site"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web_network
    restart: always

  db:
    image: postgres:15-alpine
    container_name: hk_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - web_network
    restart: always

  server:
    build: ./server
    environment:
      - "DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public"
      - "JWT_SECRET=${JWT_SECRET}"
      - PORT=3333
    depends_on:
      - db
    networks:
      - web_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`hkemprestimos.site`) && PathPrefix(`/api`)"
      - "traefik.http.routers.server.entrypoints=websecure"
      - "traefik.http.routers.server.tls.certresolver=myresolver"
      - "traefik.http.middlewares.strip-api.stripprefix.prefixes=/api"
      - "traefik.http.routers.server.middlewares=strip-api"
    restart: always

  client:
    build: ./client
    depends_on:
      - server
    networks:
      - web_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`hkemprestimos.site`)"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.routers.client.tls.certresolver=myresolver"
    restart: always

networks:
  web_network:
    name: hk_web_network

volumes:
  db_data:
